import Head from 'next/head'
import LandingHeader from '../components/LandingHeader'
import dynamic from 'next/dynamic';

export default function Home() {
  const Map = dynamic(
    () => import('../components/Map'),
    { ssr: false } // This line is important. It's what prevents server-side render
  )

  return (
    <>
      <Head>
        <title>Cheers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
          integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
          crossOrigin="" />
        <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
          integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
          crossOrigin=""></script> */}
      </Head>
      <Map/>
      <LandingHeader/>
    </>
  );
}
